---
- hosts: web
  become: true
  become_method: sudo

  tasks:
    - name: Create ~/.ssh directory
      file:
        path: ~/.ssh
        state: directory
        mode: "0700"
    - name: Copy public key to authorized_keys
      authorized_key:
        user: "muhit04"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: install nginx
      apt: name=nginx state=latest
    
    - name: start nginx
      service:
        name: nginx
        state: started

    - name: install python
      apt: name=python3 state=latest
